-- Executar como SYSADMIN
-- Camadas = bancos fixos; origem = schema (nunca criar banco por origem)

CREATE DATABASE IF NOT EXISTS RAW;
CREATE DATABASE IF NOT EXISTS STAGING;
CREATE DATABASE IF NOT EXISTS MARTS;

CREATE SCHEMA IF NOT EXISTS RAW.RECEITA_FEDERAL;
CREATE SCHEMA IF NOT EXISTS STAGING.RECEITA_FEDERAL;
