-- Executar como SYSADMIN
-- Layout dos arquivos da Receita Federal: CSV com ';', campos entre aspas, Latin-1, sem cabecalho

CREATE FILE FORMAT IF NOT EXISTS RAW.RECEITA_FEDERAL.FF_CSV
  TYPE = CSV
  FIELD_DELIMITER = ';'
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  ENCODING = 'ISO-8859-1'
  SKIP_HEADER = 0
  EMPTY_FIELD_AS_NULL = FALSE
  ESCAPE_UNENCLOSED_FIELD = NONE;

CREATE STAGE IF NOT EXISTS RAW.RECEITA_FEDERAL.STG_ARQUIVOS
  FILE_FORMAT = RAW.RECEITA_FEDERAL.FF_CSV;
