-- Executar como SYSADMIN
-- Tabelas brutas: todas as colunas VARCHAR (fiel ao arquivo) + 3 colunas de controle.
-- Tipagem e tratamento acontecem na camada STAGING.

CREATE TABLE IF NOT EXISTS RAW.RECEITA_FEDERAL.CNAE (
  CODIGO VARCHAR,
  DESCRICAO VARCHAR,
  ARQUIVO_ORIGEM VARCHAR,
  DATA_REFERENCIA DATE,
  DATA_CARGA TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW.RECEITA_FEDERAL.MOTIVO (
  CODIGO VARCHAR,
  DESCRICAO VARCHAR,
  ARQUIVO_ORIGEM VARCHAR,
  DATA_REFERENCIA DATE,
  DATA_CARGA TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW.RECEITA_FEDERAL.MUNICIPIO (
  CODIGO VARCHAR,
  DESCRICAO VARCHAR,
  ARQUIVO_ORIGEM VARCHAR,
  DATA_REFERENCIA DATE,
  DATA_CARGA TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW.RECEITA_FEDERAL.NATUREZA_JURIDICA (
  CODIGO VARCHAR,
  DESCRICAO VARCHAR,
  ARQUIVO_ORIGEM VARCHAR,
  DATA_REFERENCIA DATE,
  DATA_CARGA TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW.RECEITA_FEDERAL.PAIS (
  CODIGO VARCHAR,
  DESCRICAO VARCHAR,
  ARQUIVO_ORIGEM VARCHAR,
  DATA_REFERENCIA DATE,
  DATA_CARGA TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW.RECEITA_FEDERAL.QUALIFICACAO_SOCIO (
  CODIGO VARCHAR,
  DESCRICAO VARCHAR,
  ARQUIVO_ORIGEM VARCHAR,
  DATA_REFERENCIA DATE,
  DATA_CARGA TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW.RECEITA_FEDERAL.SIMPLES (
  CNPJ_BASICO VARCHAR,
  OPCAO_SIMPLES VARCHAR,
  DATA_OPCAO_SIMPLES VARCHAR,
  DATA_EXCLUSAO_SIMPLES VARCHAR,
  OPCAO_MEI VARCHAR,
  DATA_OPCAO_MEI VARCHAR,
  DATA_EXCLUSAO_MEI VARCHAR,
  ARQUIVO_ORIGEM VARCHAR,
  DATA_REFERENCIA DATE,
  DATA_CARGA TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW.RECEITA_FEDERAL.SOCIOS (
  CNPJ_BASICO VARCHAR,
  IDENTIFICADOR_SOCIO VARCHAR,
  NOME_SOCIO_RAZAO_SOCIAL VARCHAR,
  CPF_CNPJ_SOCIO VARCHAR,
  QUALIFICACAO_SOCIO VARCHAR,
  DATA_ENTRADA_SOCIEDADE VARCHAR,
  PAIS VARCHAR,
  REPRESENTANTE_LEGAL VARCHAR,
  NOME_REPRESENTANTE VARCHAR,
  QUALIFICACAO_REPRESENTANTE_LEGAL VARCHAR,
  FAIXA_ETARIA VARCHAR,
  ARQUIVO_ORIGEM VARCHAR,
  DATA_REFERENCIA DATE,
  DATA_CARGA TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW.RECEITA_FEDERAL.EMPRESAS (
  CNPJ_BASICO VARCHAR,
  RAZAO_SOCIAL VARCHAR,
  NATUREZA_JURIDICA VARCHAR,
  QUALIFICACAO_RESPONSAVEL VARCHAR,
  CAPITAL_SOCIAL VARCHAR,
  PORTE_EMPRESA VARCHAR,
  ENTE_FEDERATIVO_RESPONSAVEL VARCHAR,
  ARQUIVO_ORIGEM VARCHAR,
  DATA_REFERENCIA DATE,
  DATA_CARGA TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- CNPJ = arquivo "Estabelecimentos" da Receita Federal; menor grao da base (CNPJ completo de 14 digitos)
CREATE TABLE IF NOT EXISTS RAW.RECEITA_FEDERAL.CNPJ (
  CNPJ_BASICO VARCHAR,
  CNPJ_ORDEM VARCHAR,
  CNPJ_DV VARCHAR,
  IDENTIFICADOR_MATRIZ_FILIAL VARCHAR,
  NOME_FANTASIA VARCHAR,
  SITUACAO_CADASTRAL VARCHAR,
  DATA_SITUACAO_CADASTRAL VARCHAR,
  MOTIVO_SITUACAO_CADASTRAL VARCHAR,
  NOME_CIDADE_EXTERIOR VARCHAR,
  PAIS VARCHAR,
  DATA_INICIO_ATIVIDADE VARCHAR,
  CNAE_FISCAL_PRINCIPAL VARCHAR,
  CNAE_FISCAL_SECUNDARIA VARCHAR,
  TIPO_LOGRADOURO VARCHAR,
  LOGRADOURO VARCHAR,
  NUMERO VARCHAR,
  COMPLEMENTO VARCHAR,
  BAIRRO VARCHAR,
  CEP VARCHAR,
  UF VARCHAR,
  MUNICIPIO VARCHAR,
  DDD_1 VARCHAR,
  TELEFONE_1 VARCHAR,
  DDD_2 VARCHAR,
  TELEFONE_2 VARCHAR,
  DDD_FAX VARCHAR,
  FAX VARCHAR,
  CORREIO_ELETRONICO VARCHAR,
  SITUACAO_ESPECIAL VARCHAR,
  DATA_SITUACAO_ESPECIAL VARCHAR,
  ARQUIVO_ORIGEM VARCHAR,
  DATA_REFERENCIA DATE,
  DATA_CARGA TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
