-- Executar como ACCOUNTADMIN (dona das Dynamic Tables — decisao 27/08/2026:
-- sem GRANT de warehouse a SYSADMIN; a atualizacao automatica roda com a role dona)
-- STAGING: Dynamic Tables tipadas e decodificadas, 1:1 com o RAW.
-- TARGET_LAG DOWNSTREAM = atualiza quando o MARTS pedir; dominios sem consumidor
-- no MARTS usam lag proprio de 1 hora (custo zero enquanto o RAW nao muda).

CREATE OR REPLACE DYNAMIC TABLE STAGING.RECEITA_FEDERAL.CNAE
  TARGET_LAG = DOWNSTREAM WAREHOUSE = COMPUTE_WH
AS
SELECT CODIGO, DESCRICAO, DATA_REFERENCIA
FROM RAW.RECEITA_FEDERAL.CNAE;

CREATE OR REPLACE DYNAMIC TABLE STAGING.RECEITA_FEDERAL.MUNICIPIO
  TARGET_LAG = DOWNSTREAM WAREHOUSE = COMPUTE_WH
AS
SELECT CODIGO, DESCRICAO, DATA_REFERENCIA
FROM RAW.RECEITA_FEDERAL.MUNICIPIO;

CREATE OR REPLACE DYNAMIC TABLE STAGING.RECEITA_FEDERAL.NATUREZA_JURIDICA
  TARGET_LAG = DOWNSTREAM WAREHOUSE = COMPUTE_WH
AS
SELECT CODIGO, DESCRICAO, DATA_REFERENCIA
FROM RAW.RECEITA_FEDERAL.NATUREZA_JURIDICA;

CREATE OR REPLACE DYNAMIC TABLE STAGING.RECEITA_FEDERAL.MOTIVO
  TARGET_LAG = '1 hour' WAREHOUSE = COMPUTE_WH
AS
SELECT CODIGO, DESCRICAO, DATA_REFERENCIA
FROM RAW.RECEITA_FEDERAL.MOTIVO;

CREATE OR REPLACE DYNAMIC TABLE STAGING.RECEITA_FEDERAL.PAIS
  TARGET_LAG = '1 hour' WAREHOUSE = COMPUTE_WH
AS
SELECT CODIGO, DESCRICAO, DATA_REFERENCIA
FROM RAW.RECEITA_FEDERAL.PAIS;

CREATE OR REPLACE DYNAMIC TABLE STAGING.RECEITA_FEDERAL.QUALIFICACAO_SOCIO
  TARGET_LAG = '1 hour' WAREHOUSE = COMPUTE_WH
AS
SELECT CODIGO, DESCRICAO, DATA_REFERENCIA
FROM RAW.RECEITA_FEDERAL.QUALIFICACAO_SOCIO;

CREATE OR REPLACE DYNAMIC TABLE STAGING.RECEITA_FEDERAL.SIMPLES
  TARGET_LAG = DOWNSTREAM WAREHOUSE = COMPUTE_WH
AS
SELECT
  CNPJ_BASICO,
  OPCAO_SIMPLES,
  TRY_TO_DATE(DATA_OPCAO_SIMPLES, 'YYYYMMDD')    AS DATA_OPCAO_SIMPLES,
  TRY_TO_DATE(DATA_EXCLUSAO_SIMPLES, 'YYYYMMDD') AS DATA_EXCLUSAO_SIMPLES,
  OPCAO_MEI,
  TRY_TO_DATE(DATA_OPCAO_MEI, 'YYYYMMDD')        AS DATA_OPCAO_MEI,
  TRY_TO_DATE(DATA_EXCLUSAO_MEI, 'YYYYMMDD')     AS DATA_EXCLUSAO_MEI,
  DATA_REFERENCIA
FROM RAW.RECEITA_FEDERAL.SIMPLES;

-- o arquivo da Receita traz raros CNPJ_BASICO duplicados (1 caso em jul/2026, um deles
-- com cadastro vazio) — o QUALIFY garante 1 linha por CNPJ_BASICO, preferindo o preenchido
CREATE OR REPLACE DYNAMIC TABLE STAGING.RECEITA_FEDERAL.EMPRESAS
  TARGET_LAG = DOWNSTREAM WAREHOUSE = COMPUTE_WH REFRESH_MODE = FULL
AS
SELECT
  CNPJ_BASICO,
  RAZAO_SOCIAL,
  NATUREZA_JURIDICA        AS COD_NATUREZA_JURIDICA,
  QUALIFICACAO_RESPONSAVEL AS COD_QUALIFICACAO_RESPONSAVEL,
  TRY_TO_NUMBER(REPLACE(CAPITAL_SOCIAL, ',', '.'), 18, 2) AS CAPITAL_SOCIAL,
  CASE PORTE_EMPRESA
    WHEN '00' THEN 'NÃO INFORMADO'
    WHEN '01' THEN 'MICRO EMPRESA'
    WHEN '03' THEN 'EMPRESA DE PEQUENO PORTE'
    WHEN '05' THEN 'DEMAIS'
    ELSE PORTE_EMPRESA
  END AS PORTE,
  ENTE_FEDERATIVO_RESPONSAVEL,
  DATA_REFERENCIA
FROM RAW.RECEITA_FEDERAL.EMPRESAS
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY CNPJ_BASICO
  ORDER BY IFF(COALESCE(RAZAO_SOCIAL, '') = '', 1, 0), RAZAO_SOCIAL
) = 1;

CREATE OR REPLACE DYNAMIC TABLE STAGING.RECEITA_FEDERAL.SOCIOS
  TARGET_LAG = DOWNSTREAM WAREHOUSE = COMPUTE_WH
AS
SELECT
  CNPJ_BASICO,
  CASE IDENTIFICADOR_SOCIO
    WHEN '1' THEN 'PESSOA JURÍDICA'
    WHEN '2' THEN 'PESSOA FÍSICA'
    WHEN '3' THEN 'ESTRANGEIRO'
    ELSE IDENTIFICADOR_SOCIO
  END AS TIPO_SOCIO,
  NOME_SOCIO_RAZAO_SOCIAL AS NOME_SOCIO,
  CPF_CNPJ_SOCIO,
  QUALIFICACAO_SOCIO AS COD_QUALIFICACAO_SOCIO,
  TRY_TO_DATE(DATA_ENTRADA_SOCIEDADE, 'YYYYMMDD') AS DATA_ENTRADA_SOCIEDADE,
  PAIS AS COD_PAIS,
  REPRESENTANTE_LEGAL AS CPF_REPRESENTANTE_LEGAL,
  NOME_REPRESENTANTE,
  QUALIFICACAO_REPRESENTANTE_LEGAL AS COD_QUALIFICACAO_REPRESENTANTE,
  CASE FAIXA_ETARIA
    WHEN '1' THEN '00 a 12 anos'
    WHEN '2' THEN '13 a 20 anos'
    WHEN '3' THEN '21 a 30 anos'
    WHEN '4' THEN '31 a 40 anos'
    WHEN '5' THEN '41 a 50 anos'
    WHEN '6' THEN '51 a 60 anos'
    WHEN '7' THEN '61 a 70 anos'
    WHEN '8' THEN '71 a 80 anos'
    WHEN '9' THEN '80 anos ou mais'
    WHEN '0' THEN 'Não se aplica'
    ELSE FAIXA_ETARIA
  END AS FAIXA_ETARIA,
  DATA_REFERENCIA
FROM RAW.RECEITA_FEDERAL.SOCIOS;

CREATE OR REPLACE DYNAMIC TABLE STAGING.RECEITA_FEDERAL.CNPJ
  TARGET_LAG = DOWNSTREAM WAREHOUSE = COMPUTE_WH
AS
SELECT
  CNPJ_BASICO || CNPJ_ORDEM || CNPJ_DV AS CNPJ,
  CNPJ_BASICO,
  CNPJ_ORDEM,
  CNPJ_DV,
  CASE IDENTIFICADOR_MATRIZ_FILIAL
    WHEN '1' THEN 'MATRIZ'
    WHEN '2' THEN 'FILIAL'
    ELSE IDENTIFICADOR_MATRIZ_FILIAL
  END AS MATRIZ_FILIAL,
  NOME_FANTASIA,
  CASE SITUACAO_CADASTRAL
    WHEN '01' THEN 'NULA'
    WHEN '02' THEN 'ATIVA'
    WHEN '03' THEN 'SUSPENSA'
    WHEN '04' THEN 'INAPTA'
    WHEN '08' THEN 'BAIXADA'
    ELSE SITUACAO_CADASTRAL
  END AS SITUACAO_CADASTRAL,
  TRY_TO_DATE(DATA_SITUACAO_CADASTRAL, 'YYYYMMDD') AS DATA_SITUACAO_CADASTRAL,
  MOTIVO_SITUACAO_CADASTRAL AS COD_MOTIVO_SITUACAO,
  NOME_CIDADE_EXTERIOR,
  PAIS AS COD_PAIS,
  TRY_TO_DATE(DATA_INICIO_ATIVIDADE, 'YYYYMMDD') AS DATA_INICIO_ATIVIDADE,
  SUBSTR(DATA_INICIO_ATIVIDADE, 1, 4) AS ANO_INICIO,
  SUBSTR(DATA_INICIO_ATIVIDADE, 1, 6) AS ANO_MES_INICIO,
  CNAE_FISCAL_PRINCIPAL   AS COD_CNAE_PRINCIPAL,
  CNAE_FISCAL_SECUNDARIA  AS COD_CNAES_SECUNDARIOS,
  TIPO_LOGRADOURO,
  LOGRADOURO,
  NUMERO,
  COMPLEMENTO,
  BAIRRO,
  CEP,
  UF,
  MUNICIPIO AS COD_MUNICIPIO,
  DDD_1,
  TELEFONE_1,
  DDD_2,
  TELEFONE_2,
  CORREIO_ELETRONICO AS EMAIL,
  CASE
    WHEN UPPER(CORREIO_ELETRONICO) LIKE '%CONTAB%'
      OR UPPER(CORREIO_ELETRONICO) LIKE '%CONTADOR%' THEN 'E-mail Contábil'
    WHEN COALESCE(CORREIO_ELETRONICO, '') = ''       THEN 'Sem E-mail'
    ELSE 'E-mail Particular'
  END AS TIPO_EMAIL,
  CASE
    WHEN COALESCE(TELEFONE_1, '') = '' AND COALESCE(TELEFONE_2, '') = '' THEN 'Sem Telefone'
    WHEN LEFT(TELEFONE_1, 1) IN ('7', '8', '9')
      OR LEFT(TELEFONE_2, 1) IN ('7', '8', '9')                          THEN 'Celular'
    ELSE 'Telefone Fixo'
  END AS TIPO_TELEFONE,
  SITUACAO_ESPECIAL,
  TRY_TO_DATE(DATA_SITUACAO_ESPECIAL, 'YYYYMMDD') AS DATA_SITUACAO_ESPECIAL,
  DATA_REFERENCIA
FROM RAW.RECEITA_FEDERAL.CNPJ;
