-- Executar como ACCOUNTADMIN (dona das Dynamic Tables — ver 05)
-- MARTS.EMPRESAS: modelo estrela. FATO_CNPJ (grao = CNPJ 14 digitos) + dimensoes.
-- INT_* = tabelas intermediarias (agregacoes pesadas separadas do fato).
-- VW_DOMO_* = contratos de leitura do Domo (achatadas, uma por dataset do painel).

CREATE SCHEMA IF NOT EXISTS MARTS.EMPRESAS;

CREATE OR REPLACE TABLE MARTS.EMPRESAS.DIM_TEMPO AS
WITH dias AS (
  SELECT DATEADD(DAY, ROW_NUMBER() OVER (ORDER BY SEQ4()) - 1, '1900-01-01'::DATE) AS DATA
  FROM TABLE(GENERATOR(ROWCOUNT => 47848))
)
SELECT
  DATA,
  YEAR(DATA)              AS ANO,
  MONTH(DATA)             AS MES,
  DAY(DATA)               AS DIA,
  TO_CHAR(DATA, 'YYYYMM') AS ANO_MES,
  QUARTER(DATA)           AS TRIMESTRE,
  DECODE(MONTH(DATA), 1,'Janeiro', 2,'Fevereiro', 3,'Março', 4,'Abril', 5,'Maio',
         6,'Junho', 7,'Julho', 8,'Agosto', 9,'Setembro', 10,'Outubro',
         11,'Novembro', 12,'Dezembro') AS NOME_MES
FROM dias;

CREATE OR REPLACE DYNAMIC TABLE MARTS.EMPRESAS.DIM_CNAE
  TARGET_LAG = '1 hour' WAREHOUSE = COMPUTE_WH
AS
SELECT CODIGO AS COD_CNAE, DESCRICAO AS CNAE
FROM STAGING.RECEITA_FEDERAL.CNAE;

CREATE OR REPLACE DYNAMIC TABLE MARTS.EMPRESAS.DIM_MUNICIPIO
  TARGET_LAG = '1 hour' WAREHOUSE = COMPUTE_WH
AS
SELECT CODIGO AS COD_MUNICIPIO, DESCRICAO AS MUNICIPIO
FROM STAGING.RECEITA_FEDERAL.MUNICIPIO;

CREATE OR REPLACE DYNAMIC TABLE MARTS.EMPRESAS.DIM_NATUREZA_JURIDICA
  TARGET_LAG = '1 hour' WAREHOUSE = COMPUTE_WH
AS
SELECT CODIGO AS COD_NATUREZA_JURIDICA, DESCRICAO AS NATUREZA_JURIDICA
FROM STAGING.RECEITA_FEDERAL.NATUREZA_JURIDICA;

CREATE OR REPLACE DYNAMIC TABLE MARTS.EMPRESAS.INT_SOCIOS_POR_EMPRESA
  TARGET_LAG = DOWNSTREAM WAREHOUSE = COMPUTE_WH REFRESH_MODE = FULL
AS
SELECT
  CNPJ_BASICO,
  LISTAGG(NOME_SOCIO, ', ') WITHIN GROUP (ORDER BY NOME_SOCIO) AS SOCIOS,
  COUNT(*) AS QT_SOCIOS
FROM STAGING.RECEITA_FEDERAL.SOCIOS
GROUP BY CNPJ_BASICO;

CREATE OR REPLACE DYNAMIC TABLE MARTS.EMPRESAS.INT_CNAES_POR_CNPJ
  TARGET_LAG = DOWNSTREAM WAREHOUSE = COMPUTE_WH REFRESH_MODE = FULL
AS
WITH cnaes AS (
  SELECT CNPJ, COD_CNAE_PRINCIPAL AS COD_CNAE
  FROM STAGING.RECEITA_FEDERAL.CNPJ
  UNION ALL
  SELECT c.CNPJ, TRIM(s.VALUE)
  FROM STAGING.RECEITA_FEDERAL.CNPJ c,
       LATERAL SPLIT_TO_TABLE(c.COD_CNAES_SECUNDARIOS, ',') s
  WHERE COALESCE(c.COD_CNAES_SECUNDARIOS, '') <> ''
)
SELECT
  cn.CNPJ,
  LISTAGG(DISTINCT d.DESCRICAO, ', ') AS TODOS_CNAES,
  COUNT(DISTINCT cn.COD_CNAE) AS QT_CNAES
FROM cnaes cn
JOIN STAGING.RECEITA_FEDERAL.CNAE d
  ON d.CODIGO = cn.COD_CNAE
GROUP BY cn.CNPJ;

CREATE OR REPLACE DYNAMIC TABLE MARTS.EMPRESAS.FATO_CNPJ
  TARGET_LAG = DOWNSTREAM WAREHOUSE = COMPUTE_WH REFRESH_MODE = FULL
AS
SELECT
  c.CNPJ,
  c.CNPJ_BASICO,
  c.MATRIZ_FILIAL,
  e.RAZAO_SOCIAL,
  c.NOME_FANTASIA,
  COALESCE(NULLIF(TRIM(c.NOME_FANTASIA), ''), e.RAZAO_SOCIAL) AS NOME_EMPRESA,
  c.SITUACAO_CADASTRAL,
  c.DATA_SITUACAO_CADASTRAL,
  c.COD_MOTIVO_SITUACAO,
  c.DATA_INICIO_ATIVIDADE,
  c.ANO_INICIO,
  c.ANO_MES_INICIO,
  c.COD_CNAE_PRINCIPAL,
  c.COD_MUNICIPIO,
  c.UF,
  c.CEP,
  c.BAIRRO,
  c.TIPO_LOGRADOURO,
  c.LOGRADOURO,
  c.NUMERO,
  c.COMPLEMENTO,
  c.DDD_1,
  c.TELEFONE_1,
  c.DDD_2,
  c.TELEFONE_2,
  c.EMAIL,
  c.TIPO_EMAIL,
  c.TIPO_TELEFONE,
  e.COD_NATUREZA_JURIDICA,
  e.CAPITAL_SOCIAL,
  e.PORTE,
  COALESCE(si.OPCAO_SIMPLES, 'N') AS OPCAO_SIMPLES,
  si.DATA_OPCAO_SIMPLES,
  si.DATA_EXCLUSAO_SIMPLES,
  COALESCE(si.OPCAO_MEI, 'N') AS OPCAO_MEI,
  si.DATA_OPCAO_MEI,
  si.DATA_EXCLUSAO_MEI,
  so.SOCIOS,
  COALESCE(so.QT_SOCIOS, 0) AS QT_SOCIOS,
  cn.TODOS_CNAES,
  cn.QT_CNAES,
  c.DATA_REFERENCIA
FROM STAGING.RECEITA_FEDERAL.CNPJ c
JOIN STAGING.RECEITA_FEDERAL.EMPRESAS e
  ON e.CNPJ_BASICO = c.CNPJ_BASICO
LEFT JOIN STAGING.RECEITA_FEDERAL.SIMPLES si
  ON si.CNPJ_BASICO = c.CNPJ_BASICO
LEFT JOIN MARTS.EMPRESAS.INT_SOCIOS_POR_EMPRESA so
  ON so.CNPJ_BASICO = c.CNPJ_BASICO
LEFT JOIN MARTS.EMPRESAS.INT_CNAES_POR_CNPJ cn
  ON cn.CNPJ = c.CNPJ;

CREATE OR REPLACE DYNAMIC TABLE MARTS.EMPRESAS.AGG_EMPRESAS_MUNICIPIO
  TARGET_LAG = '1 hour' WAREHOUSE = COMPUTE_WH REFRESH_MODE = FULL
AS
SELECT
  f.UF,
  m.MUNICIPIO,
  f.SITUACAO_CADASTRAL,
  f.PORTE,
  f.OPCAO_SIMPLES,
  f.OPCAO_MEI,
  COUNT(*)             AS QT_CNPJ,
  SUM(f.CAPITAL_SOCIAL) AS CAPITAL_SOCIAL_TOTAL
FROM MARTS.EMPRESAS.FATO_CNPJ f
LEFT JOIN MARTS.EMPRESAS.DIM_MUNICIPIO m
  ON m.COD_MUNICIPIO = f.COD_MUNICIPIO
GROUP BY f.UF, m.MUNICIPIO, f.SITUACAO_CADASTRAL, f.PORTE, f.OPCAO_SIMPLES, f.OPCAO_MEI;

CREATE OR REPLACE DYNAMIC TABLE MARTS.EMPRESAS.AGG_EMPRESAS_CNAE
  TARGET_LAG = '1 hour' WAREHOUSE = COMPUTE_WH REFRESH_MODE = FULL
AS
SELECT
  f.UF,
  d.CNAE,
  f.SITUACAO_CADASTRAL,
  COUNT(*)             AS QT_CNPJ,
  SUM(f.CAPITAL_SOCIAL) AS CAPITAL_SOCIAL_TOTAL
FROM MARTS.EMPRESAS.FATO_CNPJ f
LEFT JOIN MARTS.EMPRESAS.DIM_CNAE d
  ON d.COD_CNAE = f.COD_CNAE_PRINCIPAL
GROUP BY f.UF, d.CNAE, f.SITUACAO_CADASTRAL;

CREATE OR REPLACE DYNAMIC TABLE MARTS.EMPRESAS.AGG_ABERTURAS_MES
  TARGET_LAG = '1 hour' WAREHOUSE = COMPUTE_WH REFRESH_MODE = FULL
AS
SELECT
  ANO_MES_INICIO,
  ANO_INICIO,
  UF,
  SITUACAO_CADASTRAL,
  OPCAO_MEI,
  COUNT(*) AS QT_CNPJ
FROM MARTS.EMPRESAS.FATO_CNPJ
GROUP BY ANO_MES_INICIO, ANO_INICIO, UF, SITUACAO_CADASTRAL, OPCAO_MEI;

CREATE OR REPLACE VIEW MARTS.EMPRESAS.VW_DOMO_EMPRESAS_MUNICIPIO AS
SELECT * FROM MARTS.EMPRESAS.AGG_EMPRESAS_MUNICIPIO;

CREATE OR REPLACE VIEW MARTS.EMPRESAS.VW_DOMO_EMPRESAS_CNAE AS
SELECT * FROM MARTS.EMPRESAS.AGG_EMPRESAS_CNAE;

CREATE OR REPLACE VIEW MARTS.EMPRESAS.VW_DOMO_ABERTURAS_MES AS
SELECT * FROM MARTS.EMPRESAS.AGG_ABERTURAS_MES;
