-- Executar como ACCOUNTADMIN
-- Relatorio analitico por CNPJ para o Domo: maximo de detalhe, recorte dos
-- 100 mil maiores CNPJs ATIVOS (matriz) por capital social. A base completa
-- (72 mi) permanece consultavel no Snowflake (MARTS.EMPRESAS.FATO_CNPJ).

CREATE OR REPLACE VIEW MARTS.EMPRESAS.VW_DOMO_CNPJ_DETALHE AS
SELECT
  SUBSTR(f.CNPJ, 1, 2) || '.' || SUBSTR(f.CNPJ, 3, 3) || '.' || SUBSTR(f.CNPJ, 6, 3)
    || '/' || SUBSTR(f.CNPJ, 9, 4) || '-' || SUBSTR(f.CNPJ, 13, 2) AS CNPJ,
  f.NOME_EMPRESA,
  f.RAZAO_SOCIAL,
  f.NOME_FANTASIA,
  f.MATRIZ_FILIAL,
  f.SITUACAO_CADASTRAL,
  f.DATA_INICIO_ATIVIDADE,
  f.ANO_INICIO,
  n.NATUREZA_JURIDICA,
  f.PORTE,
  f.CAPITAL_SOCIAL,
  c.CNAE AS CNAE_PRINCIPAL,
  LEFT(f.TODOS_CNAES, 500) AS TODOS_CNAES,
  f.QT_CNAES,
  m.MUNICIPIO,
  f.UF,
  f.CEP,
  f.BAIRRO,
  TRIM(f.TIPO_LOGRADOURO || ' ' || f.LOGRADOURO || ', ' || f.NUMERO
    || IFF(COALESCE(f.COMPLEMENTO, '') = '', '', ' - ' || f.COMPLEMENTO)) AS ENDERECO,
  IFF(COALESCE(f.TELEFONE_1, '') = '', '', '(' || f.DDD_1 || ') ' || f.TELEFONE_1) AS TELEFONE,
  f.TIPO_TELEFONE,
  f.EMAIL,
  f.TIPO_EMAIL,
  f.OPCAO_SIMPLES,
  f.OPCAO_MEI,
  LEFT(f.SOCIOS, 1000) AS SOCIOS,
  f.QT_SOCIOS,
  f.DATA_REFERENCIA
FROM MARTS.EMPRESAS.FATO_CNPJ f
LEFT JOIN MARTS.EMPRESAS.DIM_MUNICIPIO m
  ON m.COD_MUNICIPIO = f.COD_MUNICIPIO
LEFT JOIN MARTS.EMPRESAS.DIM_CNAE c
  ON c.COD_CNAE = f.COD_CNAE_PRINCIPAL
LEFT JOIN MARTS.EMPRESAS.DIM_NATUREZA_JURIDICA n
  ON n.COD_NATUREZA_JURIDICA = f.COD_NATUREZA_JURIDICA
WHERE f.SITUACAO_CADASTRAL = 'ATIVA'
  AND f.MATRIZ_FILIAL = 'MATRIZ'
ORDER BY f.CAPITAL_SOCIAL DESC NULLS LAST
LIMIT 100000;

-- Aberturas por mes: recorte a partir de 1990 (serie desde 1900 espremia o grafico)
CREATE OR REPLACE VIEW MARTS.EMPRESAS.VW_DOMO_ABERTURAS_MES AS
SELECT * FROM MARTS.EMPRESAS.AGG_ABERTURAS_MES
WHERE ANO_INICIO >= '1990';
